import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";

// Load Inter for Sans
const inter = Inter({
    variable: "--font-sans",
    subsets: ["latin"]
});

// Load JetBrains Mono for Mono
const jetBrainsMono = JetBrains_Mono({
    variable: "--font-mono",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "World Monitor Clone",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            {/* Apply both font variables to the body */}
            <body className={`${inter.variable} ${jetBrainsMono.variable} antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
