import type { Metadata } from "next";
import { Inter, Inconsolata } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import { cn } from "@/lib/utils";

// Load Inter for Sans
const inter = Inter({
    variable: "--font-sans",
    subsets: ["latin"]
});

// Load Inconsolata for Mono
const inconsolata = Inconsolata({
    variable: "--font-mono",
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "World Monitor Clone",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning className={cn("font-sans", inter.variable)}>
            <body className={`${inter.variable} ${inconsolata.variable} antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
